### ISSUE TITLE
8.5.7 install looks for 8.5.7 branch but doesn't exist

### ISSUE THREAD

**Issue by timekills** [PGBlitz/Install#3]
Error message from install script below:

TASK [Installing Version 8.5.7] *************************************************************************************************************************************
Tuesday 26 February 2019  17:27:54 +0100 (0:00:00.135)       0:00:00.195 ******
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/usr/bin/git checkout --force 8.5.7", "msg": "Failed to checkout 8.5.7", "rc": 1, "stderr": "error: pathspec '8.5.7' did not match any file(s) known to git.\n", "stderr_lines": ["error: pathspec '8.5.7' did not match any file(s) known to git."], "stdout": "", "stdout_lines": []}
...ignoring

Note script looks to pull 8.5.7 branch (non-existing.)

PGBlitz still shows update to 8.5.7 once complete, so even if fixed users may not be able to "upgrade" to 8.5.7 without deleting version tracking files.

**Comment by Admin9705** [comment]
fixed, people on the newer version of pg see it, older doesn't pulling from old repo. put an update on the old repo. once upgraded, you'll pull from the new one.
